version: '3'
services:
  back:
    build:
      context: .
      dockerfile: Dockerfile_Back
    container_name: back
    ports:
      - 8080:8080

  front:
    build: 
      context: .
      dockerfile: Dockerfile_Front
    container_name: front
    ports:
      - 4200:4200
    links:
      - back
